### ISSUE TITLE
Gpu memory

### ISSUE THREAD

**Issue by Ayanzadeh93** [tsixta/jnet#1]
Hello,

My question is about optimizing or applying the architecture to work with lower than 14GB, Is it applicable that i apply this model on the Geforce 1080Ti (11GB ram) system.

when i run this command:

python3 main.py --cuda --resolution_levels '[-2,-1,0]' --dt_bound 6 --images_idx '{"01":[],"02":[]}' --mode vis --dataset_root /path/to/DIC-C2DH-HeLa_test --model_file results/DIC-C2DH-HeLa6/model_best_train_train --output_dir results/DIC-C2DH-HeLa6

I face with this error:

return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

I will be thankful, if you help me about this issue.

**Comment by tsixta** [comment]
Hi Aydin,

I'd add random crop to data augmentation. You can do it by calling main.py with additional argument 
--aug_crop_params "[500,500]"
for example, this crops the images randomly to 500x500 px. If it still doesn't fit, try smaller values until it does.

**Comment by Ayanzadeh93** [comment]
Thank you so much for your high consideration.
